### PR TITLE
Fix GraphQL request detection on response click

### LINKED ISSUE #12: Bug: GraphQL request not detected if you click the response
There is a bug detecting the Graphql request when the user clicks and places the cursor in the response.

If I click the request and have the cursor there then the query is detected:
Image

However, when I then click the response the request is no longer detected:
Image

To get it to detect it again I have to click the Pretty view and then place my cursor in the request and then go back to the Graphql view.

### PR DESCRIPTION
**Pull request by amrelsagaei**
This Fixes #12 

## Release Notes

* **Bug Fixes**
  * Improved handling of raw response content display in GraphQL view mode to correctly distinguish between HTTP responses and regular content types.

### CODE REVIEW

File: packages/frontend/src/views/GraphQLViewMode.vue [hunk 1]
```diff
@@ -79,14 +80,27 @@ const parseHttpRaw = (raw: string) => {
...
     const editor = props.sdk.window?.getActiveEditor?.();
     if (editor !== undefined && editor !== null) {
       const editorView = editor.getEditorView();
       if (editorView !== undefined && editorView !== null) {
         const raw = editorView.state.doc.toString();
-        if (raw !== undefined && raw !== null && raw !== "") return raw;
+        if (
+          raw !== undefined &&
+          raw !== null &&
+          raw !== "" &&
```
Comment (f8thl3ss) [inline packages/frontend/src/views/GraphQLViewMode.vue]: You already do those checks in isHttpRequestRaw, you don't need ot do them 2 times.

File: packages/frontend/src/views/GraphQLViewMode.vue [hunk 2]
```diff
@@ -79,14 +80,27 @@ const parseHttpRaw = (raw: string) => {
   return { method, headers, body };
 };
 
-const getRawData = computed((): string => {
+const isHttpRequestRaw = (raw: string): boolean => {
+  if (raw === undefined || raw === "") return false;
+  const firstLine = raw.trimStart().split(/\r?\n/)[0] ?? "";
```
Comment (f8thl3ss) [inline packages/frontend/src/views/GraphQLViewMode.vue]: Once again, can you parse request using caido-sdk pls ?

File: packages/frontend/src/views/GraphQLViewMode.vue [hunk 3]
```diff
@@ -96,8 +110,27 @@ const getRawData = computed((): string => {
...
   return "";
+};
+
+const getRawData = computed((): string => {
+  const raw = resolveRawData();
+  if (raw !== "") {
+    return raw;
+  }
+
+  return cachedRawData.value;
```
Comment (f8thl3ss) [inline packages/frontend/src/views/GraphQLViewMode.vue]: Are we sure the cache is invalidated properly ? If you change request, is the cachedRawData updated properly ?

Comment (f8thl3ss) [reply packages/frontend/src/views/GraphQLViewMode.vue]: actualy, I'm not sure the cache is even needed, we should probably just do something like this:
```
  const getRawData = computed((): string => {
    if (isReplayTab.value) {
      // ... existing editor logic with isHttpRequestRaw check ...
    }

    if (props.request?.raw) {
      return props.request.raw;
    }

    return "";
  });
  ```
  and fallback to an empty string instead. Eventually the request?.raw should be non-empty

**Review by f8thl3ss — CHANGES_REQUESTED** [review]

**Comment by amrelsagaei** [comment]
@f8thl3ss dropping the cache `RequestFull` doesn't have a `method` property and `props.request?.raw` always returns the original request, not the user's edits. In replay, the editor is the source of truth since users can edit the GraphQL query/variables from the view mode and save changes back to the replay request. When the active editor switches to the response pane, we fall back to `cachedEditorView` (already existed for `saveChanges`) to keep reading from the request editor. This avoids losing edits without introducing any new caching mechanism.

File: packages/frontend/src/views/GraphQLViewMode.vue [hunk 4]
```diff
@@ -79,14 +79,37 @@ const parseHttpRaw = (raw: string) => {
...
     if (editor !== undefined && editor !== null) {
       const editorView = editor.getEditorView();
       if (editorView !== undefined && editorView !== null) {
         const raw = editorView.state.doc.toString();
-        if (raw !== undefined && raw !== null && raw !== "") return raw;
+        if (
+          raw !== undefined &&
+          raw !== null &&
+          raw !== "" &&
+          !isResponseContent(raw)
```
Comment (f8thl3ss) [inline packages/frontend/src/views/GraphQLViewMode.vue]: Can you do the null check in isResponseContentRaw instead ? It would be cleaner than copy/pasting those

**Comment by amrelsagaei** [comment]
@coderabbitai review

**Review by f8thl3ss — APPROVED** [review]
